# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  
  build-and-test:
    docker:
      - image: circleci/node:13.12
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
         
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - hold:
          type: approval
          requieres:
            - build-and-test

